# Generated by Django 5.0.2 on 2024-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_join', models.DateTimeField(auto_now_add=True, verbose_name='Последний вход')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Супер пользователь')),
            ],
            options={
                'verbose_name': 'Учетную запись',
                'verbose_name_plural': 'Учетные записи',
            },
        ),
    ]
