# Generated by Django 5.0.2 on 2024-02-13 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follower_follower_unique_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('author', 'follower')},
        ),
    ]
