# Generated by Django 5.0.2 on 2024-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='ссылка на другие сайты'),
        ),
    ]
