# Generated by Django 5.0.2 on 2024-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_description_account_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Учетная запись', 'verbose_name_plural': 'Учетные записи'},
        ),
        migrations.AlterField(
            model_name='account',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cсылка на другие сайты'),
        ),
    ]
