# Generated by Django 5.0.2 on 2024-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_options_alter_account_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Пол'),
        ),
    ]
