# Generated by Django 5.0.2 on 2024-03-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_birthday_account_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
