# Generated by Django 5.0.2 on 2024-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=50, upload_to='', verbose_name='Изображение'),
        ),
    ]
