# Generated by Django 5.0.2 on 2024-02-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_image_options_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, upload_to='', verbose_name='Видео'),
        ),
    ]
