# Generated by Django 5.0.2 on 2024-03-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0016_remove_image_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='Уведомление'),
        ),
        migrations.AddField(
            model_name='like',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='Уведомление'),
        ),
    ]
