# Generated by Django 5.0.2 on 2024-03-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_readpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post', verbose_name='Поcт'),
        ),
    ]
